services:
  dark-game:
    build:
      context: .
    container_name: dark-game
    ports: 
    - "3000:3000"
    restart: always
    networks:
    - my-network
networks:
  my-network:
    driver: bridge

  
